detectors:
  LongParameterList:
    max_params: 6
  UnusedParameters:
    enabled: true
  DuplicateMethodCall:
    max_calls: 3
  FeatureEnvy:
    enabled: false
  InstanceVariableAssumption:
    enabled: false
  IrresponsibleModule:
    enabled: false
  NestedIterators:
    max_allowed_nesting: 2
  RepeatedConditional:
    max_ifs: 3
  TooManyStatements:
    max_statements: 12
  UtilityFunction:
    public_methods_only: true

exclude_paths:
  - db/migrate
  - vendor/bundle
