Lint/UnusedMethodArgument:
  Enabled: true

Lint/AmbiguousBlockAssociation:
  Exclude:
    - spec/**/*

Lint/MissingSuper:
  Enabled: false

Metrics/AbcSize:
  Max: 23

Metrics/BlockLength:
  CountComments: false
  Max: 25
  Exclude:
    - app/views/**/*
    - config/**/*
    - lib/**/*
    - spec/**/*

Metrics/BlockNesting:
  Max: 4

Metrics/ClassLength:
  CountComments: false
  Max: 230

# Avoid complex methods.
Metrics/CyclomaticComplexity:
  Max: 6

Metrics/MethodLength:
  CountComments: false # count full line comments?
  Max: 24

Metrics/ModuleLength:
  CountComments: false
  Max: 200

Layout/LineLength:
  Max: 100
  # To make it possible to copy or click on URIs in the code, we allow lines
  # containing a URI to be longer than Max.
  AllowURI: true
  URISchemes:
    - http
    - https
  Exclude:
    - 'config/**/*'

Metrics/ParameterLists:
  Max: 5
  CountKeywordArgs: true

Metrics/PerceivedComplexity:
  Max: 12

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/GlobalStdStream:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/ModuleFunction:
  Enabled: false

AllCops:
  TargetRubyVersion: 3.3.3
  Exclude:
    - 'bin/*'
    - 'node_modules/**/*'
    - 'db/**/*'
    - 'vendor/**/*'

Style/SymbolArray:
  Enabled: false

Naming/RescuedExceptionsVariableName:
  Enabled: false
